

name: CI/CD Pipeline

# Controls when the workflow will run
on:
  push:
    branches: [main]
    
env:
  REGISTRY_NAME: deliveryserviceregistry
  CLUSTER_NAME: deliveryserviceCluster
  CLUSTER_RESOURCE_GROUP: deliveryserviceResources
  NAMESPACE: default
  APP_NAME: delivery-service
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run shell script
        run: echo commit hash is ${{ github.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deliveryService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/apnimeshap098dockerhub/delivery-service:${{ github.sha }}
